name: "Neverland Consultants"                                # CHANGE HERE 
output_dir: "."
navbar:
  title: Neverland Consultants                             # CHANGE HERE 
  type: inverse
  left:
    - text: "Principal"
      icon: fa-home
      href: index.html
    - text: "Acerca de"
      icon: fa-user 
      href: about.html
    - text: "Equipo"
      icon: fa-user 
      href: about.html
    - text: "Empresa"
      icon: fa-file-pdf-o
      href: NevCV.html
  right:
    - text: "Contacto"
      icon: fa-envelope-o
      href: mailto:luis.martinez@neverlandconsultants.capital                    # CHANGE HERE 
output:
  html_document:
    theme: cosmo
    highlight: textmate
