---
title: "Equipo"
---
# Carlos Castañeda G. 

* Entre 1980 y 2000 trabajando principalmente para Banco Nacional de México y Casa de Bolsa Inverlat, en distintos años fue director de operación de mercado de capitales, sociedades de inversión, análisis bursátil y banca de inversión. 
* En su momento estas áreas a su cargo fueron líderes en innovación y operación en la Bolsa Mexicana de Valores. Participó en la puesta en marcha de distintos productos en el mercado mexicano entre otros: Cuenta Maestra Banamex y el Mercado de Derivados.
* Del año 2000 al año 2010 se desarrollo en las direcciones de tecnología más grandes del país. Tanto en PEMEX como en el IMSS, siendo Director de Innovación y desarrollo de este último. En ambos casos se llevaron a cabo proyectos de gran tamaño,
adquiriendo vasta experiencia en procesos y tecnología. 
* Egresado del ITAM, en los últimos años ha conjuntado su
experiencia en ambas áreas, lidereando proyectos tanto financieros como de tecnología.

# Luis Martínez V.

* Egresado de Economía y Matemáticas Aplicadas del ITAM. Con más de 5 años de experiencia en el área de consultoría financiera en tecnologías de información (TI’s) y análisis económico empresarial.
* Más 2 años de experiencia en el área de banca de inversión.
* Estudios de Maestría en Finanzas por el ITAM. Investigador senior del Centro de Investigación Económica del ITAM, enfocado a la investigación de Desarrollo financiero, mercados de crédito y ahorro en el mundo e impacto de la tecnología en el Desarrollo económico.
